### ISSUE TITLE
ModuleNotFoundError when running setup.py

### ISSUE THREAD

**Issue by y-aok** [jpetrucciani/pyclickup#2]
Hello.
I am getting `ModuleNotFoundError` when installing `pyclickup`.
```
$ pip install pyclickup
Collecting pyclickup
  Downloading https://files.pythonhosted.org/packages/06/f9/7ac53e2b1f94b2cd96703a0d01ea7e17a663f5dc507d2e1c7d24e0822b29/pyclickup-0.0.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ohaa3ny1/pyclickup/setup.py", line 5, in <module>
        from pyclickup.globals import __version__, LIBRARY
      File "/tmp/pip-build-ohaa3ny1/pyclickup/pyclickup/__init__.py", line 4, in <module>
        from pyclickup.models.client import ClickUp  # noqa
      File "/tmp/pip-build-ohaa3ny1/pyclickup/pyclickup/models/client.py", line 4, in <module>
        import requests
    ModuleNotFoundError: No module named 'requests'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ohaa3ny1/pyclickup/
```

## step to reproduce the issue
1. 
```
git clone https://github.com/jpetrucciani/pyclickup.git
cd pyclickup
python3 ./setup.py develop
```

or

2. simply run `pip install pyclickup`

## reason and suggestion for fixing

* Perhaps you should not use `from pyclickup.globals import __version__, LIBRARY` under `setup.py`, since all dependencies(`requests`) may have not been installed at the point.
* `install_requires` argument is needed for `setup()` so that all dependencies will be installed after running `pip install pyclickup`.

Let me send PR soon.
Thanks.

**Comment by y-aok** [comment]
i've sent PR #3 .
please let me know if there's any concern.

**Comment by jpetrucciani** [comment]
Thanks for the PR! It is merged, and should be available on pypi as version `0.0.9`!

**Comment by jpetrucciani** [comment]
No worries! I'll get that merged as well and redeployed! Thanks again for the contributions!

**Comment by jpetrucciani** [comment]
Should be live now on PyPi as version `0.1.0`!
