### ISSUE TITLE
Add ticket creation functionality

### ISSUE THREAD

**Issue by Sergprotector** [jpetrucciani/pyclickup#5]
This is a great wrapper, thanks for creating it!  Can you add functionality to create new tickets in Clickup?  Thanks!

**Comment by jpetrucciani** [comment]
I've added some basic support for everything their current task create endpoint supports!

It is available as version `0.1.1` on pip!

https://github.com/jpetrucciani/pyclickup/releases/tag/0.1.1

**Comment by jpetrucciani** [comment]
I still need to write some documentation for this, but the method in the PyClickUp List class should show you everything you need!

**Comment by Sergprotector** [comment]
Wow, I had nowhere near this expectation.  I cannot thank you enough for
adding this!
