### ISSUE TITLE
TypeError when running Task.update()

### ISSUE THREAD

**Issue by y-aok** [jpetrucciani/pyclickup#6]
hi.
i am facing TypeError when executing `Task.update()`.

```
_task = some_task  # pyclickup.models.Task
content = _task.text_content
content += "additional comments"
_task.update(content=content)

Traceback (most recent call last):
  ### omission ###
  File "$ENV_DIR/lib/python3.6/site-packages/pyclickup/models/__init__.py", line 237, in update
    "add": [x if isinstance(x, int) else x.id for x in add_assignees],
TypeError: 'NoneType' object is not iterable
```

## reason for the issue

there are 2 for-loops used for assignees modification in `models.__init__`

```
    data = {
        "assignees": {
            "add": [x if isinstance(x, int) else x.id for x in add_assignees],
            "rem": [x if isinstance(x, int) else x.id for x in remove_assignees],
        }
    }
```

i suspect that we should not use for-loops here, since `add_assignees` `remove_assignees` are expected to be either one of:

* NoneType (default)
* int
* pyclickup.models.User

and none of the above are iterable.

## fix i can suggest

i'll make a pull request to remove these for-loops, while keeping expected types for `add_assignees` `remove_assignees` same as original code.

please note that, this PR will make the code:

* a bit redundant than original
* send blank list `[]` as `data['assignees']['add']` and `data['assignees']['rem']`, even when `add_assignees` and `remove_assignees` were `None`

please let me know about any concern you might have.
thanks.

**Comment by jpetrucciani** [comment]
Sorry about the delay here - I've been out at AWS re:Invent all week!

Thanks for the detailed issue! Let me check out the commits you had made

**Comment by y-aok** [comment]
ah, thank you! sure, i have no intention to rush you. please check this at the time convenient for you.

**Comment by y-aok** [comment]
> Do you think it makes more sense as passing a List (of int/pyclickup.models.User), or an individual add/removal?

The first one definately makes more sense to me, too. ClickUp api is also defined to receive a list as assignee related requests, so i think its more natural for models to receive arguments as lists.

That said, i don't think setting mutable objects as default arguments is a good way to go... so i recommend adding something like:

```
if add_assignees is None:
        add_assignees = []
```

and leave default arguments as they are.
i've created PR #8 based on this. i'll close my old PR #7 so please forget this one.

**Comment by y-aok** [comment]
oh, thanks for merge! so quick!

**Comment by jpetrucciani** [comment]
No problem! The new release is live and deployed on pip as version [0.1.2](https://github.com/jpetrucciani/pyclickup/releases/tag/0.1.2)!

**Comment by jpetrucciani** [comment]
Closing for now, let me know if you have any more issues/concerns here!
