### ISSUE TITLE
Feature: Add custom User-Agent value

### ISSUE THREAD

**Issue by bastbnl** [jpetrucciani/pyclickup#9]
Hi, 

Thanks for building and maintaining pyclickup.

I'm working on a system that integrates with existing system and I generally pass along a custom user agent. I've learned, from the past, that some admins really appreciate the ability to learn who's actually using their system.

I couldn't find a way to specify a custom User-Agent. PR coming up

**Comment by jpetrucciani** [comment]
Sounds like a great idea - I will review and get it merged in soon!

Thanks for contributing!

**Comment by jpetrucciani** [comment]
This is now live on pip as version [`0.1.4`](https://github.com/jpetrucciani/pyclickup/releases/tag/0.1.4).

Thanks again for your contribution! 😄
